// src/components/Footer.tsx
import React from "react";
import styled from "styled-components";
import { FaFacebook, FaGit, FaLinkedin } from "react-icons/fa";

const Footer: React.FC = () => {
  const currentYear = () => new Date().getFullYear();
  return (
    <CustomFoot>
      <CustomP>Created by Adam Håkansson. @ {currentYear()}</CustomP>
      <section>
        <Anchor href="https://www.facebook.com/adam97.live/" target="_blank">
          <FaFacebook />
        </Anchor>
        <Anchor href="https://github.com/kloparn" target="_blank">
          <FaGit />
        </Anchor>
        <Anchor
          href="https://www.linkedin.com/in/adam-h%C3%A5kansson-15942313a/"
          target="_blank"
        >
          <FaLinkedin />
        </Anchor>
      </section>
    </CustomFoot>
  );
};

const CustomP = styled.p`
  color: ${(props) => props.theme.colors.text};
`;

const CustomFoot = styled.footer`
  background-color: ${(props) => props.theme.colors.third};
  border-top: 1px solid #ccc;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 2rem;
`;

const Anchor = styled.a`
  padding: 1rem;
  font-size: 2rem;
  color: ${(props) => props.theme.colors.forth};
`;

export default Footer;

// src/lib/components/Footer.svelte
<script lang="ts">
	import GithubIcon from './icons/GithubIcon.svelte';
	import LinkedinIcon from './icons/LinkedinIcon.svelte';
	import type { Translations } from '$lib/i18n';

	let { t }: { t: Translations } = $props();
</script>

<footer class="border-t border-soft-peach/20 dark:border-accent/10">
	<div class="mx-auto flex max-w-6xl flex-col items-center gap-6 px-6 py-12 sm:flex-row sm:justify-between">
		<p class="text-sm text-text-muted">
			&copy; {new Date().getFullYear()} {t.footerText}
		</p>

		<div class="flex items-center gap-4">
			<a
				href="https://github.com/kloparn"
				target="_blank"
				rel="noopener noreferrer"
				class="flex h-10 w-10 items-center justify-center rounded-full text-text-muted transition-all hover:bg-soft-peach/20 hover:text-text dark:hover:bg-accent/10"
				aria-label="GitHub"
			>
				<GithubIcon />
			</a>
			<a
				href="https://www.linkedin.com/in/adam-h%C3%A5kansson-02a592196/"
				target="_blank"
				rel="noopener noreferrer"
				class="flex h-10 w-10 items-center justify-center rounded-full text-text-muted transition-all hover:bg-soft-peach/20 hover:text-text dark:hover:bg-accent/10"
				aria-label="LinkedIn"
			>
				<LinkedinIcon />
			</a>
		</div>
	</div>
</footer>
